Repository Mminjae/Skeleton_project, pull requests merged in 2025-04, with the labels that each got.

#13 Docs/#12/readme 리드미파일 수정
  README.md
Labels: docs

#18 fix: 초기세팅 : main.css, App.vue 변경
  package-lock.json
  project/src/App.vue
  project/src/assets/main.css
Labels: fix

#22 [feat] 초기세팅 추가 _ color / rem / font awesome / bootstrap import
  project/package.json
  project/src/assets/main.css
  project/src/main.js
Labels: fix

#26 feat: 세부 거래내역 생성_모달
  project/package-lock.json
  project/src/App.vue
  project/src/components/modal/ModalAddPost.vue
  project/src/components/modal/ModalDetailPost.vue
Labels: feat

#30 feat: 기 로그인 nav bar 레이아웃 구현
  project/package-lock.json
  project/package.json
  project/src/App.vue
  project/src/assets/main.css
  project/src/layouts/TheSidebar.vue
  project/src/layouts/TheSidebarLogin.vue
  project/src/main.js
  project/src/router/index.js
Labels: feat

#33 feat: 디렉토리 추가, 컴포넌트 이름 수정(#14)
  project/src/App.vue
  project/src/assets/css/main.css
  project/src/assets/imgs/quokka.webp
  project/src/assets/quokka.webp
  project/src/layouts/TheSidebar.vue
  project/src/views/MyPageView.vue
  project/src/views/ViewMainLogin.vue
  project/src/views/ViewMainLoginOut.vue
  project/src/views/ViewMyPage.vue
  project/src/views/ViewProfileEdit.vue
  project/src/views/ViewSign.vue
  project/src/views/ViewTransactionHistory.vue
Labels: feat

#36 feat: router -> index.js 수정, TheSidebar 주소 수정, ViewSignUp 이름 수정 (#35)
  project/src/layouts/TheSidebar.vue
  project/src/router/index.js
  project/src/views/ViewSignUp.vue
Labels: feat

#38 -feat:이전 디렉토리 삭제, main.js 수정
  project/src/main.js
  project/src/views/MembershipGuide.vue
  project/src/views/MyPageView.vue
  project/src/views/ProfileEdit.vue
  project/src/views/RecentDealView.vue
  project/src/views/TheLoginView.vue
  project/src/views/TheMainView.vue
Labels: feat

#39 fix: main.css 다시 수정
  project/src/assets/css/main.css
Labels: fix

#42 feat: CURD 모달들 디자인 틀 잡기
  project/src/App.vue
  project/src/components/modal/ModalAddPost.vue
  project/src/components/modal/ModalDeletePost.vue
  project/src/components/modal/ModalDetailPost.vue
  project/src/components/modal/ModalEditPost.vue
  project/src/components/modal/ModalExpenditure.vue
  project/src/components/modal/ModalImport.vue
Labels: feat

#47 vue.js에 레이아웃 추가
  project/src/App.vue
Labels: design

#48 Feat/#31/filter modal layout
  project/src/App.vue
  project/src/components/modal/ModalFilter.vue
  project/src/layouts/TheSidebarLogin.vue
Labels: feat

#49 refactoring: 카테고리 아이콘 컴포넌트화
  project/package-lock.json
  project/src/components/base/ExpenseIcons.vue
  project/src/components/post/PostCategoryTop.vue
  project/src/components/post/PostDonutChart.vue
  project/src/components/post/PostList.vue
  project/src/views/ViewMainLogin.vue
Labels: refactor

#52 docs: db.josn 파일 추가
  project/db.json
  project/src/views/ViewMainLogin.vue
Labels: docs

#53 design: 아이콘들 컴포넌트로 저장 #45
  project/src/components/base/iconIcon.vue
  project/src/components/base/incomeIcon.vue
Labels: design

#59 fix: icon 크기 조절 가능하도록 변경
  project/db.json
  project/src/assets/imgs/icons_layout/filter.svg
  project/src/assets/imgs/icons_layout/memo.svg
  project/src/assets/imgs/icons_layout/move_front.svg
  project/src/assets/imgs/icons_layout/move_next.svg
  project/src/assets/imgs/icons_layout/move_previous.svg
  project/src/assets/imgs/icons_layout/move_rear.svg
  project/src/assets/imgs/icons_layout/write.svg
  project/src/assets/imgs/quokka.webp
  project/src/assets/main.css
  project/src/assets/quokka.webp
  project/src/components/base/ExpenseIcons.vue
  project/src/components/base/iconIcon.vue
  project/src/components/base/incomeIcon.vue
  project/src/components/post/PostItem.vue
  project/src/layouts/TheSidebarLogin.vue
  project/src/main.js
  project/src/router/index.js
  project/src/views/ViewTransactionHistory.vue
Labels: fix

#63 design: 회원가입 css 수정(#61)
  project/src/App.vue
  project/src/assets/css/main.css
  project/src/views/ViewSign.vue
  project/src/views/ViewSignUp.vue
  project/src/views/ViewTransactionHistory.vue
Labels: design

#66 design: 사이드바(로그인)(#64)
  project/src/App.vue
  project/src/assets/imgs/logo.png
  project/src/assets/imgs/logo_msg.png
  project/src/layouts/TheSidebarLogin.vue
Labels: design

#67 Feat/#57/shon/비로그인사이드바/idpw찾기모달/비로그인메인화면
  project/src/App.vue
  project/src/components/modal/ModalIdpw.vue
  project/src/layouts/TheSidebar.vue
  project/src/layouts/TheSidebarLogin.vue
  project/src/router/index.js
  project/src/views/ViewMainLoginOut.vue
Labels: feat

#74 #72/shon 주영주성nav바 css 수정(by은우), id찾기 결과 출력창, pw변경 출력창
  project/src/App.vue
  project/src/components/modal/ModalIdpw.vue
  project/src/components/modal/ModalResetpw.vue
  project/src/components/modal/ModalResultid.vue
  project/src/layouts/TheSidebar.vue
  project/src/layouts/TheSidebarLogin.vue
Labels: feat

#77 feat: pina axios 연결 시도 #54
  project/db.json
  project/src/components/modal/ModalAddPost.vue
  project/src/components/modal/ModalIdpw.vue
  project/src/stores/transactionStore.js
Labels: feat

#82 feat: 비밀번호 유효성 검사 수정 #81
  project/src/views/ViewSignUp.vue
Labels: fix

#83 design: 모달 디자인 수정(#76)
  project/package-lock.json
  project/src/App.vue
  project/src/components/modal/ModalAddPost.vue
  project/src/components/modal/ModalEditPost.vue
  project/src/components/modal/ModalExpenditure.vue
  project/src/components/modal/ModalFilter.vue
  project/src/components/modal/ModalImport.vue
Labels: design

#85 feat: 회원가입 db연결 #80
  project/src/views/ViewSignUp.vue
Labels: feat

#86 Feat/#72/shon id/pw 찾기 창 작동 구현
  project/src/App.vue
  project/src/components/modal/ModalIdpw.vue
  project/src/components/modal/ModalResultid.vue
  project/src/layouts/TheSidebar.vue
  project/src/router/index.js
Labels: feat

#89 Feat: 최근 거래 내역 & 도넛 그래프, 카테고리별 지출 페이지네이션
  project/db.json 2.rej
  project/package-lock.json
  project/src/App.vue
  project/src/components/modal/LineGraph.vue
  project/src/components/post/PostLineGraph.vue
  project/src/components/post/PostRecent.vue
  project/src/components/post/PostRecentHistory.vue
  project/src/layouts/TheSidebarLogin.vue
  project/src/views/ViewMainLogin.vue
Labels: feat

#90 Feat: 라인그래프 (메인 하단)
  project/package-lock.json
  project/package.json
  project/src/components/post/PostLineGraph.vue
  project/src/views/ViewMainLogin.vue
  project/vite.config.js
Labels: feat

#93 feat:db.json 수정
  project/src/App.vue
  project/src/stores/userStore.js
  project/src/views/ViewMyPage.vue
  project/src/views/ViewProfileEdit.vue
Labels: feat

#94 Feat/#84/icon detail
  project/src/App.vue
  project/src/components/base/CategoryInfo.vue
  project/src/components/modal/ModalCategoryInfo.vue
  project/src/components/post/PostCategoryTop.vue
  project/src/components/post/PostItem.vue
  project/src/components/post/PostLineGraph.vue
  project/src/components/post/PostRecentHistory.vue
  project/src/layouts/TheSidebar.vue
  project/src/layouts/TheSidebarLogin.vue
  project/src/views/ViewMainLogin.vue
  project/src/views/ViewTransactionHistory.vue
Labels: feat

#95 fix: 비밀번호 유효성 검사 수정 #82
  project/src/views/ViewSignUp.vue
Labels: fix

#96 Feat/#73/final
  project/db.json
  project/package-lock.json
  project/src/App.vue
Labels: feat
